kind: pipeline
ttype: docker
name: ShakeAndCraft

trigger:
    event:
        - push

steps:
    - name: sonarqube
      image: openjdk:latest
      environment:
        SONAR_TOKEN:
          from_secret: SONAR_TOKEN
        SONAR_HOST_URL: "https://your-sonarqube-url.com"
      settings:
        sources: ./ShakeAndCraft/
      commands:
        - sonar-scanner 