kind: pipeline
ttype: docker
name: ShakeAndCraft

trigger:
    event:
        - push

steps:
  - name: install-unzip
    image: alpine
    commands:
      - apk add --no-cache unzip
  - name: install-sonar-scanner
    image: gradle:jdk11
    commands:
      - curl -sSLo /tmp/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
      - unzip -q /tmp/sonar-scanner-cli.zip -d /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/sonar-scanner-4.5.0.2216-linux/bin
  - name: sonarqube
    image: openjdk:latest
    environment:
      SONAR_LOGIN: ${SONAR_TOKEN}
      SONAR_HOST_URL: "https://your-sonarqube-url.com"
    settings:
      sources: ./ShakeAndCraft/
    commands:
      - export PATH=$PATH:/opt/sonar-scanner/sonar-scanner-4.5.0.2216-linux/bin
      - sonar-scanner 