kind: pipeline
ttype: docker
name: ShakeAndCraft

trigger:
    event:
        - push

steps:
    - name: sonarqube
      image: sonarsource/sonar-scanner-cli:4.5
      environment:
        SONAR_HOST_URL: "https://your-sonarqube-url.com"
        SONAR_LOGIN: ${SONAR_TOKEN}
      settings:
        sources: ./ShakeAndCraft/
      commands:
        - sonar-scanner 